spring:
    jackson:
        serialization.indent_output: true
    datasource:
        url: jdbc:h2:mem:expenses-it-db;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
        driver-class-name: org.h2.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none

logging.level.liquibase: INFO
logging.level.org.hibernate.SQL: info
logging.level.org.hibernate.type.descriptor.sql: info