spring:
  application:
    name: usermanagement-server
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
  jackson:
    serialization:
      write_dates_as_timestamps: false

server:
  port: 8080

liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.xml
